language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq libeigen3-dev
  - curl -s https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | sudo tar -zxvf- -C /user/local/bin

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - ctest
