language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq libeigen3-dev
  - mkdir $HOME/testspace
  - tar -zxvf testspace-linux.tgz -C $HOME/testspace

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - ctest
